# 주식 데이터 다운로드

In [ ]:
import yfinance as yf

import pandas as pd

#Apple 주식 데이터
apple = yf.Ticker("AAPL")

#다운로드
df = apple.history(period = '1y')
df.shape #(전체 데이터 수, 전체 변수 수)

(251, 7)

In [337]:
# 데이터 구경하자
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-03-05 00:00:00-05:00 to 2026-03-04 00:00:00-05:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          251 non-null    float64
 1   High          251 non-null    float64
 2   Low           251 non-null    float64
 3   Close         251 non-null    float64
 4   Volume        251 non-null    int64
 5   Dividends     251 non-null    float64
 6   Stock Splits  251 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 15.7 KB

In [338]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-03-05 00:00:00-05:00,234.398392,235.523493,228.235251,234.717010,47227600,0.0,0.0
2025-03-06 00:00:00-05:00,233.422655,236.827812,232.148211,234.308792,45170400,0.0,0.0
2025-03-07 00:00:00-05:00,234.089740,240.322569,233.741253,238.032562,46273600,0.0,0.0
2025-03-10 00:00:00-04:00,234.517865,235.135185,223.246996,226.492844,72071200,0.0,0.0
2025-03-11 00:00:00-04:00,222.838781,224.859971,216.506379,219.881668,76137400,0.0,0.0

In [339]:
df_in = pd.DataFrame(df.index, dtype="str")

In [340]:
'2025-03-05 00:00:00-05:00'.split(" ")[0]

# df의 인덱스를 Date로 변경
df = df.reset_index()

# Date값을 str로 다시 넣고 필요한 부분만 남겨두기
df["Date"] = [
    str(df["Date"][i]).split(" ")[0] for i in range(len(df))
]

#df에서 Dividends, Stock Splits 제외
df = df[["Date","Open","High","Low","Close","Volume"]]
df.head()

         Date        Open        High         Low       Close    Volume
0  2025-03-05  234.398392  235.523493  228.235251  234.717010  47227600
1  2025-03-06  233.422655  236.827812  232.148211  234.308792  45170400
2  2025-03-07  234.089740  240.322569  233.741253  238.032562  46273600
3  2025-03-10  234.517865  235.135185  223.246996  226.492844  72071200
4  2025-03-11  222.838781  224.859971  216.506379  219.881668  76137400

In [ ]:
# df에서 새로운 컬럼 추가 및 생성
# 년, 월, 일, 변화량 => 생성
df["연"] = df["Date"].apply(lambda x: x.split("-")[0])
df["월"] = df["Date"].apply(lambda x: x.split("-")[1])
df["일"] = df["Date"].apply(lambda x: x.split("-")[2])
df["변화량"] = df["Close"] - df["Open"]
df

,Date,Open,High,Low,Close,Volume,연,월,일,변화량
0,2025-03-05,234.398392,235.523493,228.235251,234.717010,47227600,2025,03,05,0.318619
1,2025-03-06,233.422655,236.827812,232.148211,234.308792,45170400,2025,03,06,0.886137
2,2025-03-07,234.089740,240.322569,233.741253,238.032562,46273600,2025,03,07,3.942822
3,2025-03-10,234.517865,235.135185,223.246996,226.492844,72071200,2025,03,10,-8.025021
4,2025-03-11,222.838781,224.859971,216.506379,219.881668,76137400,2025,03,11,-2.957113
...,...,...,...,...,...,...,...,...,...,...
246,2026-02-26,274.950012,276.109985,270.799988,272.950012,32345100,2026,02,26,-2.000000
247,2026-02-27,272.809998,272.809998,262.890015,264.179993,72366500,2026,02,27,-8.630005
248,2026-03-02,262.410004,266.529999,260.200012,264.720001,41827900,2026,03,02,2.309998
249,2026-03-03,263.480011,265.559998,260.130005,263.750000,38568900,2026,03,03,0.269989
250,2026-03-04,264.649994,266.149994,261.420013,262.519989,39258957,2026,03,04,-2.130005

In [342]:
# 연, 월, 일, 변화량 컬럼으로만 데이터프레임 생성
df1 = df[["연","월","일","변화량"]]
df1.head()

      연   월   일       변화량
0  2025  03  05  0.318619
1  2025  03  06  0.886137
2  2025  03  07  3.942822
3  2025  03  10 -8.025021
4  2025  03  11 -2.957113

In [344]:
df.rename(columns={"Date":"날짜"})

,날짜,Open,High,Low,Close,Volume,연,월,일,변화량
0,2025-03-05,234.398392,235.523493,228.235251,234.717010,47227600,2025,03,05,0.318619
1,2025-03-06,233.422655,236.827812,232.148211,234.308792,45170400,2025,03,06,0.886137
2,2025-03-07,234.089740,240.322569,233.741253,238.032562,46273600,2025,03,07,3.942822
3,2025-03-10,234.517865,235.135185,223.246996,226.492844,72071200,2025,03,10,-8.025021
4,2025-03-11,222.838781,224.859971,216.506379,219.881668,76137400,2025,03,11,-2.957113
...,...,...,...,...,...,...,...,...,...,...
246,2026-02-26,274.950012,276.109985,270.799988,272.950012,32345100,2026,02,26,-2.000000
247,2026-02-27,272.809998,272.809998,262.890015,264.179993,72366500,2026,02,27,-8.630005
248,2026-03-02,262.410004,266.529999,260.200012,264.720001,41827900,2026,03,02,2.309998
249,2026-03-03,263.480011,265.559998,260.130005,263.750000,38568900,2026,03,03,0.269989
250,2026-03-04,264.649994,266.149994,261.420013,262.519989,39258957,2026,03,04,-2.130005

In [353]:
# 볼린저 밴드의 기간
window = 20

# rolling => row 데이터에 대한 연산
df["sma_20"] = df["Close"].rolling(window=window).mean()
df["std_20"] = df["Close"].rolling(window=window).std()

df.tail()

,Date,Open,High,Low,Close,Volume,연,월,일,변화량,sma_20,std_20,bollinger_up,bollinger_down
246,2026-02-26,274.950012,276.109985,270.799988,272.950012,32345100,2026,02,26,-2.000000,268.310262,6.897796,282.105853,254.514670
247,2026-02-27,272.809998,272.809998,262.890015,264.179993,72366500,2026,02,27,-8.630005,268.617334,6.544090,281.705514,255.529154
248,2026-03-02,262.410004,266.529999,260.200012,264.720001,41827900,2026,03,02,2.309998,268.891463,6.238171,281.367805,256.415120
249,2026-03-03,263.480011,265.559998,260.130005,263.750000,38568900,2026,03,03,0.269989,268.591083,6.338108,281.267299,255.914866
250,2026-03-04,264.649994,266.149994,261.420013,262.519989,39258957,2026,03,04,-2.130005,268.255678,6.478560,281.212799,255.298557

In [ ]:
df['bollinger_up']=df.apply(lambda x: x['sma_20'] + x['std_20'] * 2, axis=1)
df['bollinger_down']=df.apply(lambda x: x['sma_20'] - x['std_20'] * 2, axis=1)
df.tail()

,Date,Open,High,Low,Close,Volume,연,월,일,변화량,sma_20,std_20,bollinger_up,bollinger_down
246,2026-02-26,274.950012,276.109985,270.799988,272.950012,32345100,2026,02,26,-2.000000,268.310262,6.897796,282.105853,254.514670
247,2026-02-27,272.809998,272.809998,262.890015,264.179993,72366500,2026,02,27,-8.630005,268.617334,6.544090,281.705514,255.529154
248,2026-03-02,262.410004,266.529999,260.200012,264.720001,41827900,2026,03,02,2.309998,268.891463,6.238171,281.367805,256.415120
249,2026-03-03,263.480011,265.559998,260.130005,263.750000,38568900,2026,03,03,0.269989,268.591083,6.338108,281.267299,255.914866
250,2026-03-04,264.649994,266.149994,261.420013,262.519989,39258957,2026,03,04,-2.130005,268.255678,6.478560,281.212799,255.298557

In [352]:
# 주식 그래프 그리기 
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=df['Date'], y=df['Close'], mode='lines', name='종가', line_color="green"), secondary_y=False)

fig.add_trace(go.Scatter(x=df['Date'], y=df['bollinger_up'], mode='lines', name='상한선', line_color="red"), secondary_y=False)
fig.add_trace(go.Scatter(x=df['Date'], y=df['bollinger_down'], mode='lines', name='하한선', line_color="blue"), secondary_y=False)

fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()